config/routes.rb
Sagepay::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users do
  	get :delete_token
  end
  resources :shops do
  	get :purchase
  end
end

app/models/token.rb
class Token < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  attr_accessible :token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def get_register_token_service_uri mode
  	if mode == "test"
  		"https://test.sagepay.com/gateway/service/directtoken.vsp"
  	elsif mode == "live"
  		"https://live.sagepay.com/gateway/service/directtoken.vsp"
  	end
  end

  def get_remove_token_service_uri mode
  	if mode == "test"
  		"https://test.sagepay.com/gateway/service/removetoken.vsp"
  	elsif mode == "live"
  		"https://live.sagepay.com/gateway/service/removetoken.vsp"
  	end
  end

  def get_direct_payment_service_uri mode
    if mode == "test"
      "https://test.sagepay.com/gateway/service/vspdirect-register.vsp"
    elsif mode == "live"
      "https://live.sagepay.com/gateway/service/vspdirect-register.vsp"
    end
  end

  def parse_response response_str
  	response_hash = Hash.new
		response_str.split(/[\r\n]+/).each {|entry|
			line = entry.split('=');
			response_hash[line[0]] = line[1];
		}
		response_hash
  end

  def generate_vendor_tx_code vendor
    vendor + "." + SecureRandom.hex(10)
  end

  def generate_direct_param request_hash
  	request_array = Array.new
		request_hash.each { |key, value|
			request_array.push key + "=" + value
		}
		request_array
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
  end

  def purchase
  	@user = User.find(current_user.id)
  	if @user.token.nil? or @user.token == ""
  		redirect_to edit_user_path(@user.id), alert: "You need to input the payment information for one-time payment." and return
  	end

  	# Create token
  	uri = URI.parse('https://test.sagepay.com/gateway/service/vspdirect-register.vsp')
  	http = Net::HTTP.new(uri.host, uri.port)
  	http.use_ssl = true
  	http.verify_mode = OpenSSL::SSL::VERIFY_NONE
		request = Net::HTTP::Post.new(uri.path)
		request_hash = Hash.new
		request_hash["VPSProtocol"]					= "3.0"
		request_hash["TxType"]							= "PAYMENT"
		request_hash["Vendor"] 							= "tonestest"
		request_hash["VendorTxCode"]				= "tonestest57113.690.870440" # increase next time, like this 870441
		request_hash["Amount"]							= "499.99"
		request_hash["Currency"]						= "GBP"
		request_hash["Token"] 							= @user.token
		request_hash["CV2"] 								= "123"
		request_hash["StoreToken"] 					= "1"
		request_hash["Description"] 				= "Personal Compter"
		request_hash["DeliveryFirstnames"] 	= "Jeff"
		request_hash["DeliverySurname"] 		= "Smith"
		request_hash["DeliveryAddress1"] 		= "1 Billing Pl"
		request_hash["DeliveryCity"] 				= "London"
		request_hash["DeliveryCountry"] 		= "GB"
		request_hash["DeliveryPostCode"] 		= "B12 3PC"
		request_hash["BillingSurname"] 			= "Smith" # need to input user info by first name and last name
		request_hash["BillingFirstnames"] 	= "Jeff"
		request_hash["BillingAddress1"] 		= "1 Billing Pl" # need to input user address
		request_hash["BillingCity"] 				= "London"
		request_hash["BillingPostcode"] 		= "B12 3PC"
		request_hash["BillingCountry"] 			= "GB"
		request_hash["Apply3DSecure"] 			= "2"

		request_array = Array.new
		request_hash.each { |key, value|
			request_array.push key + "=" + value
		}

		request.body = request_array.join('&')
		response = http.request(request)

		response_str = response.body

  	redirect_to :back, notice: response_str
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def delete_token
  	@user = User.find(params[:user_id])

  	if @user.token.nil? or @user.token == ""
  		redirect_to :back, alert: "Token is not generated..." and return
  	end

  	uri = URI.parse('https://test.sagepay.com/gateway/service/removetoken.vsp')
  	http = Net::HTTP.new(uri.host, uri.port)
  	http.use_ssl = true
  	http.verify_mode = OpenSSL::SSL::VERIFY_NONE
		request_hash = Hash.new
		request_hash["VPSProtocol"]			= "3.0"
		request_hash["TxType"]					= "REMOVETOKEN"
		request_hash["Vendor"] 					= "tonestest"
		request_hash["Token"] 					= @user.token

		request_array = Array.new
		request_hash.each { |key, value|
			request_array.push key + "=" + value
		}

		begin
			response = http.post(uri.path, request_array.join('&'))
		rescue Timeout::Error => e
			redirect_to :back, alert: "Connection timed out..." and return
		end

		response_str = response.body

		response_hash = Hash.new
		response_str.split(/[\r\n]+/).each {|entry|
			line = entry.split('=');
			response_hash[line[0]] = line[1];
		}

		# Store token
		if response_hash["Status"] == "OK" && @user.update_attributes({token: ""})
			redirect_to :back, notice: "Token is successfully removed..." and return
		else
			redirect_to :back, alert: response_str and return
		end

		redirect_to :back, notice: "Unknown error..."
  end

  def update
  	@user = User.find(params[:id])

  	# Create token
  	uri = URI.parse('https://test.sagepay.com/gateway/service/directtoken.vsp')
  	http = Net::HTTP.new(uri.host, uri.port)
  	http.use_ssl = true
  	http.verify_mode = OpenSSL::SSL::VERIFY_NONE
  	
		request_hash = Hash.new
		request_hash["VPSProtocol"]			= "3.0"
		request_hash["TxType"]					= "TOKEN"
		request_hash["Vendor"] 					= "tonestest"
		request_hash["Currency"] 				= params[:currency]
		request_hash["CardHolder"] 			= params[:card_holder_name]
		request_hash["CardNumber"] 			= params[:card_number]
		request_hash["ExpiryDate"] 			= params[:expiry_date]
		request_hash["CV2"] 						= params[:cv2]
		request_hash["CardType"] 				= params[:card_type]

		request_array = generate_direct_param request_hash

		begin
			response = http.post(uri.path, request_array.join('&'))
		rescue Timeout::Error => e
			redirect_to :back, alert: "Connection timed out..." and return
		end

		response_str = response.body

		response_hash = Hash.new
		response_str.split(/[\r\n]+/).each {|entry|
			line = entry.split('=');
			response_hash[line[0]] = line[1];
		}

		# Store token
		if response_hash["Status"] == "OK" && @user.update_attributes({token: response_hash["Token"]})
			redirect_to shops_path, notice: "You can buy the items" and return
		else
			redirect_to :back, alert: response_str and return
		end

		redirect_to :back, notice: "Unknown error..."
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p
    User: #{link_to user.name, user}

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>
<% if user_signed_in? %>
	<li><%= link_to 'Shop', shops_path %></li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Sagepay'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Sagepay'}"}
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/shops/index.html.haml
.row
	.container
		%h2 Shop
		
		%p
			%h4 [Name]   : Personal Computer
			%h4 [Amount] : 499.99$
			= link_to "Purchase", shop_purchase_path(1), class: 'btn btn-primary'

app/views/users/edit.html.haml
.row
	.container
		%h2
			Input payment information : [#{@user.name.to_s.humanize}]
		= simple_form_for(:user, :url => user_path(@user.id), :html => { :method => :put, :class => 'form-vertical' }) do |f|
			= f.error_notification
			.control-group
				.control-label.required Currency
				%input{name: :currency, value: 'GBP'}
			.control-group
				.control-label.required Card Holder's name
				%input{name: :card_holder_name, value: 'Jeff Smith'}
			.control-group
				.control-label.required Card Number
				%input{name: :card_number, value: '4929000000006'}
			.control-group
				.control-label.required Expiry Date (MMYY)
				%input{name: :expiry_date, value: '0115'}
			.control-group
				.control-label.required CV2
				%input{name: :cv2, value: '123'}
			.control-group
				.control-label.required Card Type
				%input{name: :card_type, value: 'VISA'}
			= f.button :submit, 'Publish', :class => 'btn-primary'
			= link_to 'Delete', user_delete_token_path(@user.id), class: 'btn btn-danger'

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}